/*
 * This file is generated by jOOQ.
 */
package com.luixtech.uidgenerator.usage.demo.domain;


import com.luixtech.uidgenerator.usage.demo.domain.tables.IdGeneratorWorkerNode;
import com.luixtech.uidgenerator.usage.demo.domain.tables.records.IdGeneratorWorkerNodeRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * luixdemo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<IdGeneratorWorkerNodeRecord> KEY_ID_GENERATOR_WORKER_NODE_PRIMARY = Internal.createUniqueKey(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE, DSL.name("KEY_id_generator_worker_node_PRIMARY"), new TableField[] { IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.ID }, true);
}
