/*
 * This file is generated by jOOQ.
 */
package com.luixtech.uidgenerator.usage.demo.domain;


import com.luixtech.uidgenerator.usage.demo.domain.tables.IdGeneratorWorkerNode;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Luixdemo extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>luixdemo</code>
     */
    public static final Luixdemo LUIXDEMO = new Luixdemo();

    /**
     * Worker assigner for ID generator
     */
    public final IdGeneratorWorkerNode ID_GENERATOR_WORKER_NODE = IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE;

    /**
     * No further instances allowed
     */
    private Luixdemo() {
        super("luixdemo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE);
    }
}
