/*
 * This file is generated by jOOQ.
 */
package com.luixtech.uidgenerator.usage.demo.domain;


import com.luixtech.uidgenerator.usage.demo.domain.tables.IdGeneratorWorkerNode;


/**
 * Convenience access to all tables in luixdemo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Worker assigner for ID generator
     */
    public static final IdGeneratorWorkerNode ID_GENERATOR_WORKER_NODE = IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE;
}
