/*
 * This file is generated by jOOQ.
 */
package com.luixtech.uidgenerator.usage.demo.domain.tables.daos;


import com.luixtech.uidgenerator.usage.demo.domain.tables.IdGeneratorWorkerNode;
import com.luixtech.uidgenerator.usage.demo.domain.tables.records.IdGeneratorWorkerNodeRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * Worker assigner for ID generator
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class IdGeneratorWorkerNodeDao extends DAOImpl<IdGeneratorWorkerNodeRecord, com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode, Long> {

    /**
     * Create a new IdGeneratorWorkerNodeDao without any configuration
     */
    public IdGeneratorWorkerNodeDao() {
        super(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE, com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode.class);
    }

    /**
     * Create a new IdGeneratorWorkerNodeDao with an attached configuration
     */
    @Autowired
    public IdGeneratorWorkerNodeDao(Configuration configuration) {
        super(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE, com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode.class, configuration);
    }

    @Override
    public Long getId(com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchById(Long... values) {
        return fetch(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode fetchOneById(Long value) {
        return fetchOne(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.ID, value);
    }

    /**
     * Fetch records that have <code>app_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchRangeOfAppId(String lowerInclusive, String upperInclusive) {
        return fetchRange(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.APP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchByAppId(String... values) {
        return fetch(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.APP_ID, values);
    }

    /**
     * Fetch records that have <code>host_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchRangeOfHostName(String lowerInclusive, String upperInclusive) {
        return fetchRange(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.HOST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>host_name IN (values)</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchByHostName(String... values) {
        return fetch(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.HOST_NAME, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchRangeOfType(String lowerInclusive, String upperInclusive) {
        return fetchRange(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchByType(String... values) {
        return fetch(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.TYPE, values);
    }

    /**
     * Fetch records that have <code>uptime BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchRangeOfUptime(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.UPTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uptime IN (values)</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchByUptime(LocalDate... values) {
        return fetch(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.UPTIME, values);
    }

    /**
     * Fetch records that have <code>created_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchRangeOfCreatedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.CREATED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.luixtech.uidgenerator.usage.demo.domain.tables.pojos.IdGeneratorWorkerNode> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(IdGeneratorWorkerNode.ID_GENERATOR_WORKER_NODE.CREATED_TIME, values);
    }
}
